trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: demo # <- this dash is required for variable groups

- name: dockerHubUsername
  value: 'alhjunaid'

- name: imageName
  value: 'expense-tracker'

- name: fullImageName
  value: '$(dockerHubUsername)/$(imageName)'

- name: dockerfilePath
  value: 'Dockerfile'

- name: imageTag
  value: 'latest'

steps:
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    repository: $(fullImageName)
    Dockerfile: $(dockerfilePath)
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: Push Docker image to Docker Hub
  inputs:
    command: push
    repository: $(fullImageName)
    tags: |
      $(imageTag)
    containerRegistry: $(dockerHubServiceConnection)
