trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: demo # brings in dockerHubUsername and dockerHubPassword

- name: imageName
  value: 'expense-tracker'

- name: fullImageName
  value: '$(dockerHubUsername)/$(imageName)'

- name: dockerfilePath
  value: 'Dockerfile'

- name: imageTag
  value: 'latest'

steps:
- script: |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  displayName: 'Login to Docker Hub'
  env:
    DOCKER_USERNAME: $(dockerHubUsername)
    DOCKER_PASSWORD: $(dockerHubPassword)

- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    repository: $(fullImageName)
    Dockerfile: $(dockerfilePath)
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: Push Docker image to Docker Hub
  inputs:
    command: push
    repository: $(fullImageName)
    tags: |
      $(imageTag)
